db/setup:
	./scripts/local_db.sh
.PHONY: db/setup

db/teardown:
	./scripts/local_teardown.sh
.PHONY: db/teardown

keycloak/setup:
	./scripts/keycloak_setup.sh
.PHONY: db/setup

db/teardown:
	./scripts/keycloak_teardown.sh
.PHONY: db/teardown